parameters:
    avatars_directory: '%kernel.project_dir%/public/uploads/avatars/'
    photos_directory: '%kernel.project_dir%/public/uploads/photos/'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            string $avatarsDir: '%kernel.project_dir%/public/uploads/avatars'
            string $photosDir: '%kernel.project_dir%/public/uploads/photos'
            string $encryptionKey: '%env(ENCRYPTION_KEY)%'
            string $encryptionIv: '%env(ENCRYPTION_IV)%'
            string $s3Bucket: '%env(AWS_BUCKET_NAME)%'
            string $s3Key: '%env(AWS_KEY)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    App\Service\FileUploader:
      arguments:
        $uploaders: !tagged_iterator file_uploader
    app.custom_authenticator:
      class: App\Security\CookieJWTAuthenticator
      parent: lexik_jwt_authentication.security.jwt_authenticator
