services:
  rrs-frontend:
    container_name: rrs-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
    networks:
      rrs-net:
        aliases:
          - rrs-frontend
  rrs-backend:
    container_name: rrs-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file: ./backend/.env.prod
    ports:
      - '9001:9001'
    environment:
      - APP_ENV=prod
    volumes:
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/docker-php-config.ini
    depends_on:
      - rrs-mysql
    networks:
      rrs-net:
        aliases:
          - rrs-mysql

  rrs-nginx:
    container_name: rrs-nginx
    build:
      context: .
    image: nginx:1.27-alpine
    volumes:
      - ./backend:/var/www/backend
      - ./frontend:/var/www/frontend
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/backend_host.conf:/etc/nginx/sites-enabled/backend_host.conf
    ports:
      - "5000:5000"
      - "8000:8000"
    depends_on:
      - rrs-backend
    networks:
      rrs-net:
        aliases:
          - rrs-nginx

  rrs-mysql:
    container_name: rrs-mysql
    image: mysql
    volumes:
      - ./docker/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "interview"
      MYSQL_USER: "interview"
      MYSQL_PASSWORD: "interview"
      MYSQL_ROOT_PASSWORD: "interview"
      MYSQL_TCP_PORT: 6033
    ports:
      - "6033:6033"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      rrs-net:
        aliases:
          - rrs-mysql

  rrs-mailer:
    container_name: rrs-mailer
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

networks:
  rrs-net:
    name: rrs-net
    driver: bridge
    enable_ipv6: false