FROM node:21.7.3-alpine3.20 as build

WORKDIR /usr/app
COPY ./frontend /usr/app
RUN npm ci
RUN npm run build

### Stage 2: Serve app with Nginx
FROM nginx:1.27-alpine
COPY --from=build /usr/app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]