services:
  rrs-dev-mysql:
    container_name: rrs-dev-mysql
    image: mysql
    volumes:
      - ./docker/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "interview"
      MYSQL_USER: "interview"
      MYSQL_PASSWORD: "interview"
      MYSQL_ROOT_PASSWORD: "interview"
      MYSQL_TCP_PORT: 6033
    ports:
      - "6033:6033"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      rrs-dev-net:
        aliases:
          - rrs-dev-mysql

  rrs-dev-mailer:
    container_name: rrs-dev-mailer
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
networks:
  rrs-dev-net:
    name: rrs-dev-net
    driver: bridge
    enable_ipv6: false
