services:
  cobbleweb-php:
    container_name: cobbleweb-php
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/symfony
    networks:
      cobbleweb-net:
        aliases:
          - cphp
  cobbleweb-nginx:
    container_name: cobbleweb-nginx
    image: nginx:1.27-alpine
    volumes:
      - .:/var/www/symfony
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/interview_host.conf:/etc/nginx/sites-enabled/interview_host.conf
    ports:
      - 8001:8001
    networks:
      cobbleweb-net:
        aliases:
          - cnginx
  cobbleweb-mysql:
    container_name: cobbleweb-mysql
    image: mysql
    volumes:
      - ./docker/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: "interview"
      MYSQL_USER: "interview"
      MYSQL_PASSWORD: "interview"
      MYSQL_ROOT_PASSWORD: "interview"
      MYSQL_TCP_PORT: 6033
    ports:
      - "6033:6033"
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
    networks:
      cobbleweb-net:
        aliases:
          - cmysql
  cobbleweb-mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
networks:
  cobbleweb-net:
    name: cobbleweb-net
    driver: bridge
    enable_ipv6: false
